%% This script is used to solve the wave equation. 
%In solving the wave equation we express it with Finite Difference Coefficients.
function unext = solveWaveEqn(bg,dims,srcp,source,t,unext,u,uprev)
%% Source injection & slicing
u(srcp) = u(srcp)+source(t,:);
[yj,xi] = size(u);
yj = 5:(yj-4);
xi = 5:(xi-4);
%% Wave equation
BG = bg.*bg;
dtdx = (dims.dt*dims.dt)/(dims.dx*dims.dx);
dtdz = (dims.dt*dims.dt)/(dims.dy*dims.dy);
unext(yj,xi) = 2*u(yj,xi)-uprev(yj,xi)+...
                ((dtdx*BG(yj,xi).*((-14350)*(u(yj,xi))+...
                (8064)*(u(yj,xi-1)+(u(yj,xi+1)))+...
                (-1008)*(u(yj,xi-2)+(u(yj,xi+2)))+...
                (128)*(u(yj,xi-3)+(u(yj,xi+3)))+...
                (-9)*(u(yj,xi-4)+(u(yj,xi+4))))+...
                dtdz*BG(yj,xi).*((-14350)*(u(yj,xi))+...
                (8064)*(u(yj-1,xi)+(u(yj+1,xi)))+...
                (-1008)*(u(yj-2,xi)+(u(yj+2,xi)))+...
                (128)*(u(yj-3,xi)+(u(yj+3,xi)))+...
                (-9)*(u(yj-4,xi)+(u(yj+4,xi)))))/5040);  
end